version: "3.8"
services:
  frontend:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
  backend:
    build: ./server
    container_name: server
    ports:
      - "8000:8000"
